/**
 * Generates src/lib/icon-paths.ts from lucide's icon data. Each icon's elements (path, circle, ellipse, rect,
 * line, polyline, polygon) become one path in the 0 to 1 unit box (lucide draws on a 24 by 24 grid).
 *
 *   corepack pnpm --filter @vash/web exec tsx scripts/build-icons.ts
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { type IconNode, iconNodeToPathData } from "../src/lib/svg-to-path";

const ICON_NAMES = [
  "heart", "star", "check", "x", "plus", "minus", "arrow-right", "arrow-up-right", "phone", "mail", "map-pin",
  "calendar", "clock", "camera", "image", "music", "house", "user", "users", "shopping-bag", "shopping-cart",
  "gift", "cake", "coffee", "sun", "moon", "cloud", "umbrella", "leaf", "flower", "globe", "link", "share-2",
  "bell", "message-circle", "thumbs-up", "smile", "sparkles", "zap", "flame", "crown", "award", "trophy",
  "graduation-cap", "briefcase",
];

const LABEL_OVERRIDES: Record<string, string> = {
  house: "Home",
  "share-2": "Share",
  "message-circle": "Message",
  x: "Close",
};

// lucide's "smile" is a re-export alias; the data lives in the canonical file.
const FILE_OVERRIDES: Record<string, string> = { smile: "face-slightly-smiling" };

function labelFor(name: string): string {
  if (name in LABEL_OVERRIDES) return LABEL_OVERRIDES[name]!;
  const words = name.replace(/-/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

const outFile = fileURLToPath(new URL("../src/lib/icon-paths.ts", import.meta.url));

interface LucideModule {
  __iconData: { name: string; node: IconNode };
}

const icons: { id: string; name: string; d: string }[] = [];
const skipped: string[] = [];

for (const id of ICON_NAMES) {
  let mod: LucideModule;
  try {
    // A template literal keeps TypeScript from resolving the untyped .mjs file.
    mod = (await import(`lucide-react/dist/esm/icons/${FILE_OVERRIDES[id] ?? id}.mjs`)) as LucideModule;
  } catch {
    skipped.push(id);
    continue;
  }
  icons.push({ id, name: labelFor(id), d: iconNodeToPathData(mod.__iconData.node) });
}

const header = `// Generated by apps/web/scripts/build-icons.ts from lucide (https://lucide.dev), ISC License,
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022.
// Do not edit by hand.
export interface IconPath { id: string; name: string; d: string }
export const ICONS: readonly IconPath[] = [
`;

const body = icons
  .map((icon) => `  {\n    id: ${JSON.stringify(icon.id)},\n    name: ${JSON.stringify(icon.name)},\n    d: ${JSON.stringify(icon.d)},\n  },\n`)
  .join("");

writeFileSync(outFile, `${header}${body}];\n`);
console.log(`wrote ${icons.length} icons to ${outFile}${skipped.length ? `; skipped: ${skipped.join(", ")}` : ""}`);
