/**
 * Copies the allowlisted Google Fonts (FONT_FAMILIES) from Fontsource packages into public/fonts and
 * writes the editor's @font-face stylesheet, so fonts are self-hosted (CSP font-src 'self').
 * Families keep the exact names documents use ("Inter", not Fontsource's "Inter Variable").
 *
 *   pnpm --filter @vash/web fonts:sync
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { FONT_FAMILIES } from "@vash/schema";

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public", "fonts");
const cssOut = join(root, "src", "components", "editor", "fonts.css");
const facesOut = join(root, "src", "components", "editor", "font-faces.ts");

interface Source {
  family: string;
  pkg: string;
  subsets: string[];
}

const LATIN = ["latin", "latin-ext"];
const variable = (family: string, subsets = LATIN): Source => ({ family, pkg: `@fontsource-variable/${slug(family)}`, subsets });
const fixed = (family: string, subsets = LATIN): Source => ({ family, pkg: `@fontsource/${slug(family)}`, subsets });
function slug(family: string): string {
  return family.toLowerCase().replace(/ /g, "-");
}

const SOURCES: Source[] = [
  variable("Inter"),
  variable("Roboto"),
  variable("Open Sans"),
  fixed("Poppins", ["devanagari", ...LATIN]),
  variable("Montserrat"),
  variable("Space Grotesk"),
  variable("Bricolage Grotesque"),
  fixed("Archivo Black"),
  variable("Oswald"),
  fixed("Bebas Neue"),
  variable("Playfair Display"),
  fixed("DM Serif Display"),
  fixed("Abril Fatface"),
  variable("Lora"),
  fixed("Pacifico"),
  variable("Caveat"),
  variable("Dancing Script"),
  variable("Noto Sans"),
  variable("Noto Sans Devanagari", ["devanagari", ...LATIN]),
  variable("Noto Sans Telugu", ["telugu", ...LATIN]),
];

const missing = FONT_FAMILIES.filter((f) => !SOURCES.some((s) => s.family === f));
if (missing.length) throw new Error(`No source for allowlisted fonts: ${missing.join(", ")}`);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const faces: string[] = [];
/** Per family: the weights (multiples of 100) and whether an italic ships, for the font pickers. */
const available = new Map<string, { weights: Set<number>; italic: boolean }>();
const licences: string[] = [];
let bytes = 0;

for (const s of SOURCES) {
  const dir = dirname(require.resolve(`${s.pkg}/package.json`));
  const isVariable = s.pkg.startsWith("@fontsource-variable/");
  const sheets = readdirSync(dir).filter((f) => (isVariable ? /^wght(-italic)?\.css$/.test(f) : /^\d{3}(-italic)?\.css$/.test(f)));
  const subsetOf = new RegExp(`^${slug(s.family)}-(${s.subsets.join("|")})-(?!ext-)`);
  for (const sheet of sheets) {
    const css = readFileSync(join(dir, sheet), "utf8");
    for (const block of css.matchAll(/@font-face\s*{([^}]*)}/g)) {
      const body = block[1]!;
      const file = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(body)?.[1];
      if (!file || !subsetOf.test(file)) continue;
      copyFileSync(join(dir, "files", file), join(outDir, file));
      bytes += readFileSync(join(outDir, file)).length;
      const get = (prop: string) => new RegExp(`${prop}:\\s*([^;]+);`).exec(body)?.[1]?.trim();
      const [lo = 400, hi = lo] = (get("font-weight") ?? "400").split(/\s+/).map(Number);
      const entry = available.get(s.family) ?? { weights: new Set<number>(), italic: false };
      for (let w = Math.ceil(lo / 100) * 100; w <= hi; w += 100) entry.weights.add(w);
      if (get("font-style") === "italic") entry.italic = true;
      available.set(s.family, entry);
      faces.push(
        [
          "@font-face {",
          `  font-family: "${s.family}";`,
          `  font-style: ${get("font-style")};`,
          `  font-weight: ${get("font-weight")};`,
          "  font-display: swap;",
          `  src: url(/fonts/${file}) format("woff2");`,
          `  unicode-range: ${get("unicode-range")};`,
          "}",
        ].join("\n"),
      );
    }
  }
  const licence = join(dir, "LICENSE");
  if (existsSync(licence)) licences.push(`== ${s.family} (${s.pkg}) ==\n${readFileSync(licence, "utf8").trim()}`);
}

writeFileSync(
  cssOut,
  `/* Generated by scripts/sync-fonts.ts from Fontsource; do not edit. Licences: public/fonts/LICENSES.txt (SIL OFL 1.1). */\n\n${faces.join("\n\n")}\n`,
);
const table = SOURCES.map((s) => {
  const a = available.get(s.family)!;
  return `  ${JSON.stringify(s.family)}: { weights: [${[...a.weights].sort((x, y) => x - y).join(", ")}], italic: ${a.italic} },`;
});
writeFileSync(
  facesOut,
  `/* Generated by scripts/sync-fonts.ts; do not edit. The weights and italics each self-hosted family ships. */\n\nexport const FONT_FACES: Record<string, { weights: readonly number[]; italic: boolean }> = {\n${table.join("\n")}\n};\n`,
);
writeFileSync(join(outDir, "LICENSES.txt"), `${licences.join("\n\n")}\n`);
console.log(`${SOURCES.length} families, ${faces.length} faces, ${(bytes / 1024).toFixed(0)} KB of woff2`);
