/* Generated by scripts/sync-fonts.ts; do not edit. The weights and italics each self-hosted family ships. */

export const FONT_FACES: Record<string, { weights: readonly number[]; italic: boolean }> = {
  "Inter": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: true },
  "Roboto": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: true },
  "Open Sans": { weights: [300, 400, 500, 600, 700, 800], italic: true },
  "Poppins": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: true },
  "Montserrat": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: true },
  "Space Grotesk": { weights: [300, 400, 500, 600, 700], italic: false },
  "Bricolage Grotesque": { weights: [200, 300, 400, 500, 600, 700, 800], italic: false },
  "Archivo Black": { weights: [400], italic: false },
  "Oswald": { weights: [200, 300, 400, 500, 600, 700], italic: false },
  "Bebas Neue": { weights: [400], italic: false },
  "Playfair Display": { weights: [400, 500, 600, 700, 800, 900], italic: true },
  "DM Serif Display": { weights: [400], italic: true },
  "Abril Fatface": { weights: [400], italic: false },
  "Lora": { weights: [400, 500, 600, 700], italic: true },
  "Pacifico": { weights: [400], italic: false },
  "Caveat": { weights: [400, 500, 600, 700], italic: false },
  "Dancing Script": { weights: [400, 500, 600, 700], italic: false },
  "Noto Sans": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: true },
  "Noto Sans Devanagari": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: false },
  "Noto Sans Telugu": { weights: [100, 200, 300, 400, 500, 600, 700, 800, 900], italic: false },
};
